### ISSUE TITLE
hex sticker design issue

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/board#3]
board package의 hex sticker 디자인을 해보려고 하는데요.
패키지에 대한 간단한 소개 + 이름을 지은 목적에 대해서 reply 해주시면 참고해 보도록 하겠습니다.

**Comment by jhk0530** [comment]
데이터 분석 작업중에 쓰이는 EDA 결과를 만들어내는 package 입니다. (with shiny)
결과를 보여준다는 의미로 `board`라고 지었어요. (알림판)

**Comment by YoungjunNa** [comment]
알림판! 네 고맙습니다 !!
